exclude: cloudfront-auth
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.0
  hooks:
  - id: yamllint
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
  rev: v2.0.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.47.0
  hooks:
  - id: terraform_docs
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.12
  hooks:
  - id: terraform-fmt
  - id: terragrunt-hclfmt
  - id: terraform-validate
  - id: tflint
  - id: shellcheck
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 1.0.816
  hooks:
  - id: checkov
- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
  - id: codespell
    args:
    - --quiet-level=2
    - --check-filenames
    - --check-hidden
    - --ignore-words=.codespell-ignore
